<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>JsonRpcKit.Reference</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="OpenRpcReference.html" />
  </ItemGroup>
</Project>
